# Generated by Django 4.2.5 on 2023-10-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
