# Generated by Django 4.2.5 on 2023-10-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('scientific_name', models.CharField(max_length=50)),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='pets.pet')),
            ],
        ),
    ]
