# Generated by Django 4.2.5 on 2023-10-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_created_at_alter_group_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pets',
        ),
    ]
